In [4]:
import torch

In [5]:

block_size: int = 1024
vocab_size: int = 100277 #100000 BPE merges, 256 bytes tokens, 21 per i token specializ
n_embd: int = 768 #dimensione embedding 
n_layers: int = 12 #numero di blocchi
n_head: int = 12 #numero di teste di attenzione

In [6]:
a = torch.arange(0, 10, 2)
a

tensor([0, 2, 4, 6, 8])

In [57]:
theta = 1 / (10000 ** ((torch.arange(0, (n_embd // n_head), 2)).float() / (n_embd // n_head)))

In [58]:
theta

tensor([1.0000e+00, 7.4989e-01, 5.6234e-01, 4.2170e-01, 3.1623e-01, 2.3714e-01,
        1.7783e-01, 1.3335e-01, 1.0000e-01, 7.4989e-02, 5.6234e-02, 4.2170e-02,
        3.1623e-02, 2.3714e-02, 1.7783e-02, 1.3335e-02, 1.0000e-02, 7.4989e-03,
        5.6234e-03, 4.2170e-03, 3.1623e-03, 2.3714e-03, 1.7783e-03, 1.3335e-03,
        1.0000e-03, 7.4989e-04, 5.6234e-04, 4.2170e-04, 3.1623e-04, 2.3714e-04,
        1.7783e-04, 1.3335e-04])

In [59]:
pos_idx = torch.arange(block_size, dtype=torch.float)

In [60]:
pos_idx

tensor([0.0000e+00, 1.0000e+00, 2.0000e+00,  ..., 1.0210e+03, 1.0220e+03,
        1.0230e+03])

In [61]:
pos_idx.shape, theta.shape

(torch.Size([1024]), torch.Size([32]))

In [62]:
idx_theta = torch.einsum('i,j->ij', pos_idx, theta)
idx_theta.shape, idx_theta.dtype

(torch.Size([1024, 32]), torch.float32)

In [78]:
cache = torch.stack([torch.cos(idx_theta), torch.sin(idx_theta)], dim=-1)

In [79]:
x = torch.randn(3, 4, 5, dtype=torch.bfloat16)
y = torch.ones(3, 4, 5)
x + y

tensor([[[ 0.0977,  0.6992,  2.5312,  2.0703,  4.0938],
         [ 1.1245,  0.9019,  2.6484, -0.2734, -0.3906],
         [ 2.2500,  2.0234,  1.2295,  2.2109,  1.6562],
         [ 0.7383,  1.9414,  3.1250,  1.4121,  0.5547]],

        [[ 0.3906,  0.8818,  2.4844,  2.5938,  1.6953],
         [ 1.0522,  1.5586, -0.5781,  3.7500,  1.2871],
         [-0.1484, -0.3125,  2.0391,  0.7441,  0.6055],
         [ 0.6348,  1.8203,  1.1641,  1.2012, -0.2266]],

        [[-0.5078,  1.2695,  0.7998,  1.2324,  2.4609],
         [-1.7969,  0.4180,  1.5625,  1.0248, -0.9766],
         [-1.5938,  0.4688,  2.2578,  1.3535,  1.0188],
         [-0.6953,  0.6426,  1.2832,  1.5352,  0.5391]]])